from .settings import *

__all__ = [
    'UBIDOTS_API_KEY',
    'CONFIDENCE_THRESHOLD',
    'VERIFICATION_TIME',
    'VERIFICATION_CONFIDENCE',
    'EYE_EAR_THRESHOLD',
    'MOUTH_EAR_THRESHOLD',
    'DETECTION_INTERVAL',
    'PUBLISH_INTERVAL',
    'FRAME_WIDTH',
    'FRAME_HEIGHT',
    'USERS',
    'FACE_CASCADE_PATH',
    'SHAPE_PREDICTOR_PATH',
    'FACE_RECOGNIZER_MODEL'
]